server:
  port: 8080

spring:
  application:
    name: QTDL

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qtdl
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Log SQL queries
  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type: trace